platform :ios, '9.0'

use_frameworks!

target 'PundiPrintei_Example' do
  pod 'PundiPrintei', :path => '../'
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
